version: '3.1'

networks:
    video_net:

services:
           
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password 
        volumes:
            - ./script/create_table.sql:/data/application/init.sql
            - ~/datadrive/toolbox/video/mysql/:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: toolbox_video
        networks:
            - video_net
        
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        image: dennis199441/toolbox-video-service:latest
        restart: always
        volumes:
            - ~/datadrive/toolbox/video/application/log/:/usr/src/app/log
            - ~/datadrive/toolbox/video/application/input/:/usr/src/app/input
            - ~/datadrive/toolbox/video/application/output/:/usr/src/app/output
        environment:
            PORT: 8080
            VIDEO_SERVICE_SQL_INSTANCE: db
            VIDEO_SERVICE_DB_USER: root
            VIDEO_SERVICE_DB_PASSWORD: root
            VIDEO_SERVICE_DB_NAME: toolbox_video
            DB_PORT: 3306
            JWT_SECRET_STRING: try-to-guess-the-secret
            WAIT_HOSTS: db:3306
        ports: 
            - 8080:8080
        networks:
            - video_net
        depends_on:
            - db
